# Generated by Django 3.0 on 2020-03-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200324_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='last_updated_by',
            field=models.CharField(default='管理员', max_length=50, null=True, verbose_name='最后更新人'),
        ),
        migrations.AlterField(
            model_name='education',
            name='last_updated_by',
            field=models.CharField(default='管理员', max_length=50, null=True, verbose_name='最后更新人'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_updated_by',
            field=models.CharField(default='管理员', max_length=50, null=True, verbose_name='最后更新人'),
        ),
    ]
