# Generated by Django 3.0 on 2020-03-24 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200324_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Education'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(choices=[('doctor', '博士'), ('master', '硕士研究生'), ('bachelor', '学士'), ('other', '其它')], default='学士', max_length=50, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('colleage', '大学'), ('high', '高中'), ('junior', '初中'), ('primary', '小学')], default='大学', max_length=50, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.BooleanField(choices=[('F', '女'), ('M', '男')], default='男', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital',
            field=models.CharField(choices=[('married', '已婚'), ('unmarried', '未婚'), ('divorce', '离异')], default='未婚', max_length=15, verbose_name='婚姻状况'),
        ),
    ]
