# Generated by Django 3.0 on 2020-03-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200324_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('F', '女'), ('M', '男')], default='男', max_length=2, verbose_name='性别'),
        ),
    ]
